openapi: 3.0.0
info:
  title: Warmane Analytics API
  description: This API provides the interface into the data to find out how much of a dog a player might be
  version: 1.0.0
paths:
  /character:
    get:
      summary: Get Warmane character data
      description: Proxies to Warmane's API and passes user search parameters to the Warmane Crawler.
      parameters:
        - name: character
          in: query
          required: true
          schema:
            type: string
        - name: realm
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved character data
      x-amazon-apigateway-integration:
        httpMethod: POST
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        uri: "arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${warmane_analytics_api_v2_main_function_arn}/invocations"
    options:
      responses:
        200:
          description: CORS headers
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
      x-amazon-apigateway-integration:
        httpMethod: POST
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        uri: "arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${warmane_analytics_api_v2_main_function_arn}/invocations"
  /crawl:
    post:
      summary: Start Warmane character data crawl
      description: Initiates a crawl of Warmane character data based on the user search parameters provided.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                character:
                  type: string
                realm:
                  type: string
              required:
                - character
                - realm
              additionalProperties: false
      responses:
        200:
          description: Crawl started successfully
      x-amazon-apigateway-integration:
        httpMethod: POST
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        uri: "arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${warmane_analytics_api_v2_main_function_arn}/invocations"
    options:
      responses:
        200:
          description: CORS headers
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
      x-amazon-apigateway-integration:
        httpMethod: POST
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        uri: "arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${warmane_analytics_api_v2_main_function_arn}/invocations"
