name: Continuous Deployment
on:
  push:
  pull_request:
    branches:
      - v2
  workflow_dispatch:
    inputs:
      branch:
        required: true
        description: specify the branch that you want deployed
        default: v2
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: npm install

      - name: prettier
        run: npm run prettier

      - name: eslint
        run: npm run eslint

      - name: test
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: echo "artifact_version=$(git symbolic-ref --short HEAD)" >> $GITHUB_ENV
      - run: sudo apt-get update && sudo apt-get install -y zip
      - run: npm install
      - run: npm run build
      - run: npm install --production
      - run: cp -r node_modules build
      - run: cd build/ && zip -r ../$(git symbolic-ref --short HEAD).zip .
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: aws s3 cp ./${{ env.artifact_version }}.zip s3://simoni-enterprises-artifacts/${GITHUB_REPOSITORY}/${{ env.artifact_version }}.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    env:
      TF_WORKSPACE: dev
    steps:
      - uses: actions/checkout@v3
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: get artifact file name
        run: echo "artifact_file=${GITHUB_REPOSITORY}/${inputs.branch}.zip" >> $GITHUB_ENV

      - name: terraform format
        id: fmt
        run: terraform fmt -check

      - name: terraform init
        id: init
        run: terraform init

      - name: terraform validate
        id: validate
        run: terraform validate -no-color

      - name: terraform plan
        id: plan
        run: terraform plan -var="artifact_file=${{ env.artifact_file }}" -no-color -input=false

      - name: terraform apply dev
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: terraform apply -var="artifact_file=${{ env.artifact_file }}" -auto-approve -input=false

      - name: terraform apply prod
        if: github.ref == 'refs/heads/v2' && github.event_name == 'push'
        run: terraform apply -var="artifact_file=${{ env.artifact_file }}" -auto-approve -input=false
        env:
          TF_WORKSPACE: prod
